import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    < div className={styles.container}>
      <Head>
        <titledddddddd>Create Next App</titledddddddd>
        <meta 
          name="description" 
          content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      
    </>
  )
}
